# Generated by Django 3.2.14 on 2022-07-17 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=10),
        ),
    ]
