name: Deploy Cloudformation Stack

on:
  push:
    branches:    
      - 'main'

jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy ECR CFN stack
      continue-on-error: true
      id: ecr
      uses: mgenteluci/cloudformation-deploy-action@v1.4.1
      env:
        TEMPLATE: ${{ secrets.ECR_TEMPLATE_PATH }}
        AWS_STACK_NAME: ${{ secrets.SERVICE_NAME }}-ECR
        AWS_REGION: ${{ secrets.REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        PARAMETER_OVERRIDES: >
          RepositoryName=${{ secrets.SERVICE_NAME }}-web-app

    - name: Get ECR Arn
      id: ecr-arn
      run: |
        ECRArn=$(aws cloudformation --region ${{ secrets.REGION }} describe-stacks |
        --stack-name ${{ secrets.SERVICE_NAME }}-ECR |
        --query "Stacks[0].Outputs[?Export=='ECRArn'].OutputValue" --output text)

        echo "ECR Arn: $ECRArn"
        echo "::set-output name=ecr-arn::$ECRArn"

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}


    