name: Deploy Cloudformation Stack

on:
  push:
    branches:    
      - 'main'
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      ecr-template-path:
        description: 'CFN template path for the ECR inside repo'
        required: true
        default: 'deploy/cloudformation/registry.yaml'
      service-name:
        description: 'Name of the service this template will be used in'
        required: true
        default: 'addresses'

jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy ECR CFN stack
      id: ecr
      uses: mgenteluci/cloudformation-deploy-action@v1.4.1
      env:
        TEMPLATE: ${{ github.event.inputs.ecr-template-path }}
        AWS_STACK_NAME: ${{ github.event.inputs.service-name }}-ECR
        AWS_REGION: ${{ github.event.inputs.region }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        PARAMETER_OVERRIDES: >
          RepositoryName=${{ github.event.inputs.service-name }}-web-app

    - name: Get ECR Arn
      id: ecr-arn
      run: |
        aws cloudformation --region ${{ github.event.inputs.region }} describe-stacks --stack-name ${{ github.event.inputs.service-name }}-ECR


    